//------------------------------------------------------------------------------
// <auto-generated>
//     Este código foi gerado para declarar os controles de Default.aspx.
//     Atualize manualmente caso adicione novos controles ao markup.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoPessoalWebForms
{
	public partial class Default
	{
		/// <summary>
		/// Controle form1.
		/// </summary>
		protected global::System.Web.UI.HtmlControls.HtmlForm form1;
	}
}
